

# Image Source Settings
image_sources:
  nicfi:
    source_name: "NICFI"
    project_path: "projects/planet-nicfi/assets/basemaps/americas"
    scale_meters: 5

    
  sentinel:
    source_name: "SENTINEL-2"
    project_path: "COPERNICUS/S2_SR_HARMONIZED"
    scale_meters: 10


Shared_Assets_ID: "projects/ee-qinheyi/assets/1823_ADRSM"
  
